### PR TITLE
Adds static System function for jumping to System Bootloader

### PR DESCRIPTION
**Pull request by Tom97531**
Related to https://github.com/electro-smith/libDaisy/issues/328

### CODE REVIEW

**Comment by stephenhensley** [comment]
This is small enough that I should be able to give it a quick test and get it merged today. 

Everything looks good on first glance.

Thanks for the contribution!

**Comment by stephenhensley** [comment]
@Tom97531 you may have noticed the failed CI-check.

For formatting, we use clang-format to do code styling. There is a `.clang-format` file in the repo. So if you have the "Clang-Format" extension by Xaver in VS Code, you can format while you work. 

Otherwise we have a `fix_style.sh` script in the base level of libdaisy that can be run to clean it up after-the-fact. This is probably the quickest way to fix up what you've got here.

You can also verify that it will pass CI by using the following helper script:
`./ci/run-clang-format.py -r src/` 

It'll return any issues, or nothing if there are no problems. 

Let me know if you have any questions.

**Comment by Tom97531** [comment]
Thanks for your feedback !
I have just pushed the changes to fit the format.

**Comment by Tom97531** [comment]
Great !
This will be my first contribution to an active open source project ! Makes me happy :)

**Comment by stephenhensley** [comment]
Apologies for the delay on this one, but it tests okay!

Thanks again for the contribution, and welcome to the world of open source! We're happy to have you around!

**Comment by Tom97531** [comment]
No problem for the delay, glad to be here !

**Pull request merged**
