### PR TITLE
USB Host / MSD functionality

### PR DESCRIPTION
**Pull request by CorvusPrudens**
Currently, the integration hasn't been tested, but an initial review will probably bring up necessary changes anyway.

The primary changes to look for (besides all those brought in from `dfu_compatible`), are:
- src/hid/msd.h
- src/hid/msd.cpp
- src/usbh/
- Middlewares/ST/STM32_USB_Host_Library/
- src/util/fatfs_usbh.c / .h
- src/util/usbh_diskio.c / .h

### CODE REVIEW

**Comment by CorvusPrudens** [comment]
[USB Host/MSD libDaisy PR](https://trello.com/c/Z3N3PloD/246-usb-host-msd-libdaisy-pr)

**Comment by TheSlowGrowth** [comment]
Would love to give this a review but at 89 commits and 10.000 lines of changes, it's just too big to handle. Can we split this up a bit?

**Comment by stephenhensley** [comment]
@TheSlowGrowth Hahaha yeah it's huge.

This is based off the bootloader additions branch (another pretty large one), but once that's merged the overall changes should go down quite a bit here.

The other huge chunk of changes here is just adding the new middleware files. So I think once all the other changes are merged in this should look a bit cleaner.

**Comment by CorvusPrudens** [comment]
Note -- it seems like these additions have caused the logger class to have unreliable startup. That'll have to be looked into.

**Comment by stephenhensley** [comment]
closing PR as this is split up into #432 #433 and #434 now

**Pull request closed without merging**
