### PR TITLE
Feature/UI system

### LINKED ISSUE #202: UI Event Queue
This relates to #201 

To help users design their software more cleanly, it would be helpful to have a UI event queue that can queue user input events like

1. button pressed
2. button released
3. encoder turned
4. potentiometer turned
5. SD card added or removed (?)

Let's discuss what features would be required and how this could be integrated into the daisy framework.

### LINKED ISSUE #203: Knob Monitor class
This relates to #202  and #201 

With a UI event queue, users may want to have a simple way of adding potentiometer-related events to the queue. Here's how I would imagine such a class:

- takes a reference to the UI event queue in the ctor
- has a deadband within which no movement events will be generated. This helps reduce ADC noise and limit the number of events generated
- can differentiate between knobs that are currently being touched and knobs that are idle - applying different deadbands to both

Assuming we have the programming model proposed in #201, using such a monitor could be used like this:

````
constexpr int numPots = 6;
PotMonitor<numPots> potMonitor(myEventQueue);

// called from a low prio timer IRQ
void scan()
{
    float newPotValues[numPots];

    // get current values for all pots and store that in the array. This would be done by another class
    // ...

    // pass the values to the monitor that reads them and generates UI queue events as needed
    potMonitor.readPots(newPotValues);
}
````

### LINKED ISSUE #204: Button Monitor class
Much like #203 a monitor class for buttons would be helpful.

Suggested features

- takes reference to the UI evene queue in its ctor
- has s single `process()` function that would be called from the `scan()` function of the application (as suggested in #201 ). This function would add events to the queue and also do debouncing, repetition when the button is held down, etc.
- Buttons can potentially be connected in a million ways. To keep virtual function calls and other runtime overhead low while still allowing unlimited hardware connections, we could have the button monitor use a backend like this:
````
class MyButtonDataBackend
{
public:
    // called when the monitor starts a new round of button scanning. Multiplexed button reader classes that use shift registers, etc. could use this function to read all the data at once.
    void startScanning();
    // called when the monitor wants to knot the state of a single button
    bool getButtonState(int index);
    // called after the monitor is done. This can be used to trigger async hardware operations like ADC reads, etc. if required.
    void stopScanning();
}

constexpr int numButtons = 10;
ButtonMonitor<MyButtonDataBackend, numButtons> bttnMonitor(myUiEventQueue);

// called from a low prio timer IRQ
void scan()
{
    bttnMonitor.process();
}
````

We could provide some default backends, e.g. a simple GPIO backend, a 74HC165 backend, etc.

### PR DESCRIPTION
**Pull request by TheSlowGrowth**
This PR adds a full UI system that I've been using for various projects now.

This is the basic idea:

- hardware drivers (`PotMonitor `and `ButtonMonitor`) add events to a `UiEventQueue`
- A `UI` object has a stack of `UiPage`s to which it distributes events from the UiEventQueue.
- Multiple Canvases (represented by a `void*`) are used to draw the `UiPage`s on the actual hardware. Such a canvas is completely generic and could be a bunch of LEDs, a text display, a graphics display, etc. Inside the `UiPage` the `void*` of the canvas can be casted to whatever output device it represents, keeping the UI system generic enough to be useful for almost any form of user interface.

This can be used to create various user interfaces - from simple to very complex. As a useful example, I added a menu page that can be used to select between various items, call functions, open other menus, modify float/int/enum values, etc. Other pages and dialogs are possible, e.g. file picker dialogs.

I'll try to create an example for the examples repo. I only have my Seed and my custom boards, but I'll try to make an example for the Field / Patch (?)

This PR 
- fixes #202 
- fixes #203 
- fixes #204

### CODE REVIEW

**Comment by stephenhensley** [comment]
This looks great! Thanks for the contribution! I'll look over all of this, and try it out over the next few days.

I've been carrying around the Mutable-Instruments UI/EventQueue on the last few projects I've done to see how it would fit with libdaisy. And while it does work well for a minimal interface, this looks like it is a lot more conducive to complex UIs with displays, alternate modes, etc.

I'll be happy to test whichever example platform you make it for. It seems like more people have the Patch. So that might be a bit more universally appreciated.

**Comment by TheSlowGrowth** [comment]
I'm still working on a good example. I realised I could make the example much tidier, if I added in a bunch of the other stuff that I had planned for a later PR. So ... things are taking a bit longer than expected. We're getting close, though.

**Comment by TheSlowGrowth** [comment]
Okay, so I think this is starting to take shape now.

Here's what's missing:
- Proper documentation in the form of a wiki article and a tutorial. This should be as simple to use and as easy to understand as possible. The code documentation is quite verbose but I think the overall concepts are not directly visible yet.
- An example in the DaisyExamples repo (working on this already)
- An EncoderMonitor
- Unit tests for the UI class
- Unit tests for the monitor classes
- I'd like to add another version of the AbstractMenu class that's more suitable to larger screens. I'm thinking of something like a list box - a little like the Elektron menus - where multiple items are displayed at once.

Before I move on with these things, I'd like to collect some feedback on the concepts and ideas in this PR. I would rather solidify these things before I put in the time to write the additional documentation. Feel free to suggest improvements or ask questions at any time. I'm totally open to changes!

I know, not having a full tutorial makes this PR probably a little more difficult to understand. I'd be happy to give a little introduction via some other medium, maybe a GoToMeeting/Zoom/Jitsi? Let me know if that sounds good to you.

**Comment by stephenhensley** [comment]
Thanks for the update!

I admit I've only given it a cursory glance so far since there were a lot of parts in motion. I can look this over in depth when I go through the other PRs tomorrow/Wednesday, and get you some feedback.

Having some reference code of it being used (even if it's not complete) would be helpful to look at just to get an idea of what it'll look like for users, but I understand that you're still getting that put together.

Once I've had a chance to look it over a bit, I'll let you know if something like a video chat would be good to go over details, but it might not be necessary. So we'll cross that bridge when we get to it.

Again, thanks for the absolutely _massive_ update! I think once this is in place, it'll really start to feel like a drop-in instrument/synth programming environment (instead of a bunch of hardware handlers that you can do stuff with).

**Comment by TheSlowGrowth** [comment]
I found some time today to write a [small example for the Daisy Patch](https://github.com/TheSlowGrowth/DaisyExamples/tree/feature/UiSystemDemo/patch/UiSystemDemo). It's not a full tutorial, but better than nothing :-)
You'll have to use [the feature branch fo this PR](https://github.com/TheSlowGrowth/libDaisy/tree/feature/UiSystem) when building this, obviously ;-)

**Comment by stephenhensley** [comment]
Nice! Thanks for sharing the example, that definitely makes it a bit easier to look over.

I am going to try to get through a few of these other PRs today. So I've only taken a quick look so far. 

Having used the Mutable-Instruments UI/EventQueue set up quite a bit, the overall pattern here is pretty familiar. Which is nice, especially since I'm sure a bunch of other people have seen that before.

The menu item config is quite verbose, but seems really extensible. So that's totally fine (thanks for including all of the comments throughout the example. _Super_ helpful.

Overall on a brief review it's looking like it's in a pretty good spot. I'm going to spend a bit of time over the next few days looking over it to see how it fits with non-display oriented user interfaces (since that's most of what I deal with on a day-to-day, and seems most common in the eurorack space in general).

Once I've had a chance to actually run it on the Patch, and explore a bit more I'll give a bit more feedback as well.

**Comment by recursinging** [comment]
So I just flashed the example onto my bluemchen module with its 64x32 OLED, and everything except the "popup" worked flawlessly.  The example is fantastic and really shows the capabilities of this feature.  It also showed me that a legible, usable UI really is possible on the tiny OLED of my module.

I was not familiar with this particular design pattern, and although quite complicated, every thing seems logically placed.  Let's face it though, designing and implementing an interactive UI is just a complicated task, which is difficult to get right.  The layout of this feature definitely makes it easier once you've grokked the pattern.  

I need a bit to flesh out why the popup example isn't working on the bluemchen, but otherwise, I'd love to see this PR get merged. Hat off to @TheSlowGrowth - fantastic work.

**Comment by TheSlowGrowth** [comment]
@recursinging Thanks for giving it a try! The popup should appear when pressing the encoder while the "Popup" menu item is selected. What happened on your screen?
I'd love to take a look at what the menus look like on the small screen (I only have a 128x64 to test with). I wrote the drawing functions so that they'll choose a smaller font size if required, so I would hope that the test is still readable, but I've never seen it.
Maybe your Popup-issue is related to the fact that I didn't test it on a small screen. Maybe it's drawn outside of the screen bounds or something weird like that.

**Comment by recursinging** [comment]
Here's a little video of the example on the bluemchen...

https://user-images.githubusercontent.com/27807726/118976996-f81e9c80-b975-11eb-8f4c-74fb53f2a8c3.mp4

When I click the encoder on the popup page, the module locks up and needs a reset...  I'll step through with the debugger when I get a chance.

**Comment by TheSlowGrowth** [comment]
I just rebased this on top of the current master + the CpuLoadMeter branch. That branch contains the TestIsolator which I need for some of the tests here in this PR.

I thought about the LookAndFeel for a while and decided to remove it again. It's nice to be able to swap out the design for individual pages ... but unfortunately, combining all drawing routines in a single LookAndFeel class means that all of them will ALWAYS be included in the binary. With the constrained flash memory, I think this is not worth the added flexibility. 

I've been using the UI system in my reverb/delay module for a while now and implemented a couple of custom UI pages there. So far, I haven't found anything else that I would like to change, so I'm removing the WIP state from this PR.

**Comment by TheSlowGrowth** [comment]
Rebased to master

**Comment by stephenhensley** [comment]
Now that I got through the rest of the recent PRs, this one's next! I should have some time Thursday or Friday to try the things I wanted to, and then I'll be signing off. From my read-throughs so far everything seems solid. 

Just want to see about making a UI with a few LEDs instead of a display since that's most of what I'll be using it for on larger projects.

**Comment by stephenhensley** [comment]
Alright!

Finally had a chance to build a little test UI for an LED display. I think this is solid!

I did not use the higher level `AbstractMenu` class, and simply used the UiPage as the base class, though I could see the AbstractMenu stuff being useful for more complex UIs.

Overall, once the boiler plate stuff set up, it was pretty easy to set up a custom UI page, and it can definitely accomplish what I'm used to doing with the lighter-weight ui setup I've been using. The additional monitor classes, espeically the `PotMonitor` are very welcome additions.

It did take me a little bit to figure out that the way to check if the `OnButton` call to the UiPage was rising/falling, but having the `numberOfPresses` be 0 makes perfect sense.

Everything's really modular, and seems quite user friendly. Great job, and thanks SO much for this massive contribution!

**Pull request merged**
